name: Validate

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Validate repository contents
        run: ./scripts/validate_open_source.sh
